%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                              plotFigE5
% author - Brad Rauscher (created 2024)
% 
% Plots figure panels for Extended Data Figure 5. Must run 
% MAIN_plotFigures.m first.
% 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

close all

% calculate subject averages
NE_order = order(NE_Idx);

tmp_data = struct;
tmp_data.g_LR_perf = f_regImages(Fig2.LR_perf, refParcellation, ...
    settings.allen_masks, 0) .* BM;
tmp_data.g_IRFx2_perf = f_regImages(Fig2.IRFx2_perf, refParcellation, ...
    settings.allen_masks, 0) .* BM;
tmp_data.Unf.LR_perf = f_regImages(unfiltered.LR_perf, refParcellation, ...
    settings.allen_masks, 0) .* BM;
tmp_data.Unf.IRFx2_perf = f_regImages(unfiltered.IRFx2_perf, ...
    refParcellation, settings.allen_masks, 0) .* BM;
tmp_data.Shu.LR_perf = f_regImages(shuffled.LR_perf, refParcellation, ...
    settings.allen_masks, 0) .* BM;
tmp_data.Shu.IRFx2_perf = f_regImages(shuffled.IRFx2_perf, ...
    refParcellation, settings.allen_masks, 0) .* BM;
tmp_data.Unf.LR_A = f_regImages(unfiltered.LR_A, refParcellation, ...
    settings.allen_masks, 0) .* BM;
tmp_data.Unf.LR_B = f_regImages(unfiltered.LR_B, refParcellation, ...
    settings.allen_masks, 0) .* BM;
tmp_data.Unf.IRFx2_A = f_regImages(unfiltered.IRFx2_A, refParcellation, ...
    settings.allen_masks, 0) .* BM;
tmp_data.Unf.IRFx2_B = f_regImages(unfiltered.IRFx2_B, refParcellation, ...
    settings.allen_masks, 0) .* BM;
tmp_data.Shu.LR_A = f_regImages(shuffled.LR_A, refParcellation, ...
    settings.allen_masks, 0) .* BM;
tmp_data.Shu.LR_B = f_regImages(shuffled.LR_B, refParcellation, ...
    settings.allen_masks, 0) .* BM;
tmp_data.Shu.IRFx2_A = f_regImages(shuffled.IRFx2_A, refParcellation, ...
    settings.allen_masks, 0) .* BM;
tmp_data.Shu.IRFx2_B = f_regImages(shuffled.IRFx2_B, refParcellation, ...
    settings.allen_masks, 0) .* BM;

subAvg.FigE5.LR_perf = NaN(500, 600, M_NE);
subAvg.FigE5.IRFx2_perf = NaN(500, 600, M_NE);
subAvg.FigE5.Unf.LR_perf = NaN(500, 600, M_NE);
subAvg.FigE5.Unf.IRFx2_perf = NaN(500, 600, M_NE);
subAvg.FigE5.Unf.LR_A = NaN(500, 600, M_NE);
subAvg.FigE5.Unf.LR_B = NaN(500, 600, M_NE);
subAvg.FigE5.Unf.IRFx2_A = NaN(500, 600, M_NE);
subAvg.FigE5.Unf.IRFx2_B = NaN(500, 600, M_NE);
subAvg.FigE5.Unf.tA = NaN(M_NE, 1);
subAvg.FigE5.Unf.tB = NaN(M_NE, 1);
subAvg.FigE5.Unf.IRFx2_IRF = NaN(151, 2, M_NE);
subAvg.FigE5.Shu.LR_A = NaN(500, 600, M_NE);
subAvg.FigE5.Shu.LR_B = NaN(500, 600, M_NE);
subAvg.FigE5.Shu.IRFx2_A = NaN(500, 600, M_NE);
subAvg.FigE5.Shu.IRFx2_B = NaN(500, 600, M_NE);
subAvg.FigE5.Shu.tA = NaN(M_NE, 1);
subAvg.FigE5.Shu.tB = NaN(M_NE, 1);
subAvg.FigE5.Shu.IRFx2_IRF = NaN(151, 2, M_NE);

for i = 1:M_NE
    subAvg.FigE5.LR_perf(:, :, i) = mean( ...
        tmp_data.g_LR_perf(:, :, NE_order(i).Runs), 3, 'omitnan');
    subAvg.FigE5.IRFx2_perf(:, :, i) = mean( ...
        tmp_data.g_IRFx2_perf(:, :, NE_order(i).Runs), 3, 'omitnan');
    subAvg.FigE5.Unf.LR_perf(:, :, i) = mean( ...
        tmp_data.Unf.LR_perf(:, :, NE_order(i).Runs), 3, 'omitnan');
    subAvg.FigE5.Unf.IRFx2_perf(:, :, i) = mean( ...
        tmp_data.Unf.IRFx2_perf(:, :, NE_order(i).Runs), 3, 'omitnan');
    subAvg.FigE5.Shu.LR_perf(:, :, i) = mean( ...
        tmp_data.Shu.LR_perf(:, :, NE_order(i).Runs), 3, 'omitnan');
    subAvg.FigE5.Shu.IRFx2_perf(:, :, i) = mean( ...
        tmp_data.Shu.IRFx2_perf(:, :, NE_order(i).Runs), 3, 'omitnan');
    subAvg.FigE5.Unf.LR_A(:, :, i) = mean( ...
        tmp_data.Unf.LR_A(:, :, NE_order(i).Runs), 3, 'omitnan');
    subAvg.FigE5.Unf.LR_B(:, :, i) = mean( ...
        tmp_data.Unf.LR_B(:, :, NE_order(i).Runs), 3, 'omitnan');
    subAvg.FigE5.Unf.IRFx2_A(:, :, i) = mean( ...
        tmp_data.Unf.IRFx2_A(:, :, NE_order(i).Runs), 3, 'omitnan');
    subAvg.FigE5.Unf.IRFx2_B(:, :, i) = mean( ...
        tmp_data.Unf.IRFx2_B(:, :, NE_order(i).Runs), 3, 'omitnan');
    subAvg.FigE5.Unf.LR_tA(i) = mean([unfiltered.LR_tA{NE_order(i).Runs}]);
    subAvg.FigE5.Unf.LR_tB(i) = mean([unfiltered.LR_tB{NE_order(i).Runs}]);
    subAvg.FigE5.Unf.IRFx2_IRF(:, :, i) = mean( ...
        cat(3, unfiltered.IRFx2_IRF{NE_order(i).Runs}), 3);
    subAvg.FigE5.Shu.LR_A(:, :, i) = mean( ...
        tmp_data.Shu.LR_A(:, :, NE_order(i).Runs), 3, 'omitnan');
    subAvg.FigE5.Shu.LR_B(:, :, i) = mean( ...
        tmp_data.Shu.LR_B(:, :, NE_order(i).Runs), 3, 'omitnan');
    subAvg.FigE5.Shu.IRFx2_A(:, :, i) = mean( ...
        tmp_data.Shu.IRFx2_A(:, :, NE_order(i).Runs), 3, 'omitnan');
    subAvg.FigE5.Shu.IRFx2_B(:, :, i) = mean( ...
        tmp_data.Shu.IRFx2_B(:, :, NE_order(i).Runs), 3, 'omitnan');
    subAvg.FigE5.Shu.LR_tA(i) = mean([shuffled.LR_tA{NE_order(i).Runs}]);
    subAvg.FigE5.Shu.LR_tB(i) = mean([shuffled.LR_tB{NE_order(i).Runs}]);
    subAvg.FigE5.Shu.IRFx2_IRF(:, :, i) = mean( ...
        cat(3, shuffled.IRFx2_IRF{NE_order(i).Runs}), 3);
end

fig_savePath = fullfile(savePath, 'ExtDataFig5');
[~, ~, ~] = mkdir(fig_savePath);

%% Extended Data Fig 5A

f = figure;
f_plotMap(mean(subAvg.FigE5.Unf.LR_A, 3, 'omitnan') .* plotBM, ...
    cmp = cmpbbr, ...
    clim = [-1, 1]);
colorbar off;

exportgraphics(f, fullfile(fig_savePath, 'ExtDataFig5_A1.jpg'), ...
    Resolution = 300, ...
    BackgroundColor = [1, 1, 1]);

f = figure;
f_plotMap(mean(subAvg.FigE5.Unf.LR_B,3, 'omitnan') .* plotBM, ...
    cmp = cmpbbr, ...
    clim = [-1, 1]);
colorbar off;

exportgraphics(f, fullfile(fig_savePath, 'ExtDataFig5_A2.jpg'), ...
    Resolution = 300, ...
    BackgroundColor = [1, 1, 1]);

%% Extended Data Fig 5B

barData = {};
barData{1} = subAvg.FigE5.Unf.LR_tA / 10;
barData{2} = subAvg.FigE5.Unf.LR_tB / 10;

f = figure;
[dataMean, dataSEM] = f_plotBar(barData, ...
    colors = [c_Ca; c_GRAB], ...
    legend = {'tA', 'tB'}, ...
    ylabel = 'r', ...
    title = 'Timing Coefficients', ...
    ylim = [-0.2, 1]);

saveas(f, fullfile(fig_savePath, 'ExtDataFig5_B.svg'));

T = table({order(NE_Idx).Mouse}', barData{1}', barData{2}', ...
    VariableNames = {'Mouse', 'tA', 'tB'});
writetable(T, fullfile(fig_savePath, 'ExtDataFig5_B.csv'));

%% Extended Data Fig 5C

f = figure;
f_plotMap(mean(subAvg.FigE5.Unf.LR_perf, 3, 'omitnan') .* plotBM, ...
    cmp = cmpvir, ...
    clim = [0, 1]);
colorbar off;

exportgraphics(f, fullfile(fig_savePath, 'ExtDataFig5_C.jpg'), ...
    Resolution = 300, ...
    BackgroundColor = [1, 1, 1]);

%% Extended Data Fig 5D

f = figure;
f_plotMap((mean(subAvg.FigE5.Unf.LR_perf, 3, 'omitnan') - ...
    mean(subAvg.Fig2.g_LR_perf, 3, 'omitnan')) .* plotBM, ...
    cmp = cmpbbr, ...
    clim = [-1, 1]);
colorbar off;

exportgraphics(f, fullfile(fig_savePath, 'ExtDataFig5_D.jpg'), ...
    Resolution = 300, ...
    BackgroundColor = [1, 1, 1]);

%% Extended Data Fig 5E

f = figure;
f_plotMap(mean(subAvg.FigE5.Unf.IRFx2_A, 3, 'omitnan') .* plotBM, ...
    cmp = cmpbbr, ...
    clim = [-1, 1]);
colorbar off;

exportgraphics(f, fullfile(fig_savePath, 'ExtDataFig5_E1.jpg'), ...
    Resolution = 300, ...
    BackgroundColor = [1, 1, 1]);

f = figure;
f_plotMap(mean(subAvg.FigE5.Unf.IRFx2_B, 3, 'omitnan') .* plotBM, ...
    cmp = cmpbbr, ...
    clim = [-1, 1]);
colorbar off;

exportgraphics(f, fullfile(fig_savePath, 'ExtDataFig5_E2.jpg'), ...
    Resolution = 300, ...
    BackgroundColor = [1, 1, 1]);

%% Extended Data Fig 5F

t = -5 : 0.1 : 10;

f = figure;
meanSig1 = mean(subAvg.FigE5.Unf.IRFx2_IRF(:, 1, :), 3);
error1 = std(subAvg.FigE5.Unf.IRFx2_IRF(:, 1, :), 0, 3) / sqrt(M_NE);
f_plotLineError(t, meanSig1, error1, ...
    color = c_Ca);

meanSig2 = mean(subAvg.FigE5.Unf.IRFx2_IRF(:, 2, :), 3);
error2 = std(subAvg.FigE5.Unf.IRFx2_IRF(:, 2, :), 0, 3) / sqrt(M_NE);
f_plotLineError(t, meanSig2, error2, ...
    color = c_GRAB, ...
    xlim = [-2, 7], ...
    xlabel = 'Time (s)', ...
    ylabel = 'a.u.', ...
    legend = {'IRF(t_0^A,\tau_A)','IRF(t_0^B,\tau_B)'}, ...
    title = 'Double IRF');

idx = 30 : 120;

T = table(t(idx)', meanSig1(idx), meanSig2(idx), error1(idx), ...
    error2(idx), VariableNames = {'Time', 'IRF_Ca', 'IRF_NE', 'SEM_Ca', ...
    'SEM_NE'});
writetable(T, fullfile(fig_savePath, 'ExtDataFig5_F.csv'));
saveas(f, fullfile(fig_savePath, 'ExtDataFig5_F.svg'));

%% Extended Data Fig 5G

f = figure;
f_plotMap(mean(subAvg.FigE5.Unf.IRFx2_perf, 3, 'omitnan') .* plotBM, ...
    cmp = cmpvir, ...
    clim = [0, 1]);
colorbar off;

exportgraphics(f, fullfile(fig_savePath, 'ExtDataFig5_G.jpg'), ...
    Resolution = 300, ...
    BackgroundColor = [1, 1, 1]);

%% Extended Data Fig 5H

f = figure;
f_plotMap((mean(subAvg.FigE5.Unf.IRFx2_perf, 3, 'omitnan') - ...
    mean(subAvg.Fig2.g_IRFx2_perf, 3, 'omitnan')) .* plotBM, ...
    cmp = cmpbbr, ...
    clim = [-1, 1]);
colorbar off;

exportgraphics(f, fullfile(fig_savePath, 'ExtDataFig5_H.jpg'), ...
    Resolution = 300, ...
    BackgroundColor = [1, 1, 1]);

%% Extended Data Fig 5I

f = figure;
f_plotMap(mean(subAvg.FigE5.Shu.LR_A, 3, 'omitnan') .* plotBM, ...
    cmp = cmpbbr, ...
    clim = [-1, 1]);
colorbar off;

exportgraphics(f, fullfile(fig_savePath, 'ExtDataFig5_I1.jpg'), ...
    Resolution = 300, ...
    BackgroundColor = [1, 1, 1]);

f = figure;
f_plotMap(mean(subAvg.FigE5.Shu.LR_B, 3, 'omitnan') .* plotBM, ...
    cmp = cmpbbr, ...
    clim = [-1, 1]);
colorbar off;

exportgraphics(f, fullfile(fig_savePath, 'ExtDataFig5_I2.jpg'), ...
    Resolution = 300, ...
    BackgroundColor = [1, 1, 1]);

%% Extended Data Fig 5J

barData = {};
barData{1} = subAvg.FigE5.Shu.LR_tA / 10;
barData{2} = subAvg.FigE5.Shu.LR_tB / 10;

f = figure;
[dataMean, dataSEM] = f_plotBar(barData, ...
    colors = [c_Ca; c_GRAB], ...
    legend = {'tA', 'tB'}, ...
    ylabel = 'r', ...
    title = 'Timing Coefficients', ...
    ylim = [-0.2, 1]);

saveas(f, fullfile(fig_savePath, 'ExtDataFig5_J.svg'));

T = table({order(NE_Idx).Mouse}', barData{1}', barData{2}', ...
    VariableNames = {'Mouse', 'tA', 'tB'});
writetable(T, fullfile(fig_savePath, 'ExtDataFig5_J.csv'));

%% Extended Data Fig 5K

f = figure;
f_plotMap((mean(subAvg.FigE5.Shu.LR_perf, 3, 'omitnan') - ...
    mean(subAvg.Fig1.inv_perf, 3, 'omitnan')) .* plotBM, ...
    cmp = cmpbbr, ...
    clim = [-1, 1]);
colorbar off;

exportgraphics(f, fullfile(fig_savePath, 'ExtDataFig5_K.jpg'), ...
    Resolution = 300, ...
    BackgroundColor = [1, 1, 1]);

%% Extended Data Fig 5L

f = figure;
f_plotMap(mean(subAvg.FigE5.Shu.IRFx2_A, 3, 'omitnan') .* plotBM, ...
    cmp = cmpbbr, ...
    clim = [-1, 1]);
colorbar off;

exportgraphics(f, fullfile(fig_savePath, 'ExtDataFig5_L1.jpg'), ...
    Resolution = 300, ...
    BackgroundColor = [1, 1, 1]);

f = figure;
f_plotMap(mean(subAvg.FigE5.Shu.IRFx2_B, 3, 'omitnan') .* plotBM, ...
    cmp = cmpbbr, ...
    clim = [-1, 1]);
colorbar off;

exportgraphics(f, fullfile(fig_savePath, 'ExtDataFig5_L2.jpg'), ...
    Resolution = 300, ...
    BackgroundColor = [1, 1, 1]);

%% Extended Data Fig 5M

t = -5 : 0.1 : 10;

f = figure;
meanSig1 = mean(subAvg.FigE5.Shu.IRFx2_IRF(:, 1, :), 3);
error1 = std(subAvg.FigE5.Shu.IRFx2_IRF(:, 1, :), 0, 3) / sqrt(M_NE);
f_plotLineError(t, meanSig1, error1, ...
    color = c_Ca);

meanSig2 = mean(subAvg.FigE5.Shu.IRFx2_IRF(:, 2, :), 3);
error2 = std(subAvg.FigE5.Shu.IRFx2_IRF(:, 2, :), 0, 3) / sqrt(M_NE);
f_plotLineError(t, meanSig2, error2, ...
    color = c_GRAB, ...
    xlim = [-2, 7], ...
    xlabel = 'Time (s)', ...
    ylabel = 'a.u.', ...
    legend = {'IRF(t_0^A,\tau_A)','IRF(t_0^B,\tau_B)'}, ...
    title = 'Double IRF');

idx = 30 : 120;

T = table(t(idx)', meanSig1(idx), meanSig2(idx), error1(idx), ...
    error2(idx), VariableNames = {'Time', 'IRF_Ca', 'IRF_NE', 'SEM_Ca', ...
    'SEM_NE'});
writetable(T, fullfile(fig_savePath, 'ExtDataFig5_M.csv'));
saveas(f, fullfile(fig_savePath, 'ExtDataFig5_M.svg'));

%% Extended Data Fig 5N

f = figure;
f_plotMap((mean(subAvg.FigE5.Shu.IRFx2_perf, 3, 'omitnan') - ...
    mean(subAvg.Fig1.inv_perf, 3, 'omitnan')) .* plotBM, ...
    cmp = cmpbbr, ...
    clim = [-1, 1]);
colorbar off;

exportgraphics(f, fullfile(fig_savePath, 'ExtDataFig5_N.jpg'), ...
    Resolution = 300, ...
    BackgroundColor = [1, 1, 1]);

%% Extended Data Fig 5O

barData = {};
barData{1} = squeeze(mean(subAvg.Fig1.inv_perf .* plotBM, [1, 2], 'omitnan'));
barData{2} = squeeze(mean(subAvg.Fig1.SSp_perf .* plotBM, [1, 2], 'omitnan'));
barData{3} = squeeze(mean(subAvg.Fig1.var_perf .* plotBM, [1, 2], 'omitnan'));
barData{4} = squeeze(mean(subAvg.FigE5.LR_perf .* plotBM, [1, 2], 'omitnan'));
barData{5} = squeeze(mean(subAvg.FigE5.IRFx2_perf .* plotBM, [1, 2], 'omitnan'));
barData{6} = squeeze(mean(subAvg.FigE5.Unf.LR_perf .* plotBM, [1, 2], 'omitnan'));
barData{7} = squeeze(mean(subAvg.FigE5.Unf.IRFx2_perf .* plotBM, [1, 2], 'omitnan'));
barData{8} = squeeze(mean(subAvg.FigE5.Shu.LR_perf .* plotBM, [1, 2], 'omitnan'));
barData{9} = squeeze(mean(subAvg.FigE5.Shu.IRFx2_perf .* plotBM, [1, 2], 'omitnan'));

f = figure;
[dataMean, dataSEM] = f_plotBar(barData, ...
    colors = [repmat(c_Yellow, 3, 1); repmat(c_darkCyan, 2, 1); ...
    repmat(c_Ca, 2, 1); repmat(c_pupil, 2, 1)], ...
    ylabel = 'r', ...
    title = 'Model Performance Comparison', ...
    ylim = [0, 1]);

[h, p] = f_kstest(barData, 0.01);

T = NaN(M, 9);
T(:, 1) = barData{1};
T(:, 2) = barData{2};
T(:, 3) = barData{3};
T(NE_Idx, 4) = barData{4};
T(NE_Idx, 5) = barData{5};
T(NE_Idx, 6) = barData{6};
T(NE_Idx, 7) = barData{7};
T(NE_Idx, 8) = barData{8};
T(NE_Idx, 9) = barData{9};

saveas(f, fullfile(fig_savePath, 'ExtDataFig5_O.svg'));
T = table({order.Mouse}', T(:, 1), T(:, 2), T(:, 3), T(:, 4), T(:, 5), ...
    T(:, 6), T(:, 7), T(:, 8), T(:, 9), VariableNames = {'Mouse', ...
    'global', 'SSp', 'variant', 'Linear Regression', 'Double IRF', ...
    'Unf Linear Regression', 'Unf Double IRF', ...
    'Shuffled Linear Regression', 'Shuffled Double IRF'});
writetable(T, fullfile(fig_savePath, 'ExtDataFig5_O.csv'));

labels = {'global', 'SSp', 'variant', 'Linear Regression', ...
    'Double IRF', 'Unfiltered Linear Regression', ...
    'Unfiltered Double IRF', 'Shuffled Linear Regression', ...
    'Shuffled Double IRF'};

T = table;
for i = 1 : numel(labels)
    T.(labels{i}) = p(:, i);
end
writetable(T, fullfile(fig_savePath, 'ExtDataFig5_O_p.csv'));