%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                              plotFigE7
% author - Brad Rauscher (created 2024)
% 
% Plots figure panels for Extended Data Figure 7. Must run 
% MAIN_plotFigures.m first.
% 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

close all

% calculate subject averages
NE_order = order(NE_Idx);

subAvg.FigE7.lowF_lowNE_Ca = NaN(12, 12, M_NE);
subAvg.FigE7.lowF_highNE_Ca = NaN(12, 12, M_NE);
subAvg.FigE7.medF_lowNE_Ca = NaN(12, 12, M_NE);
subAvg.FigE7.medF_highNE_Ca = NaN(12, 12, M_NE);
subAvg.FigE7.highF_lowNE_Ca = NaN(12, 12, M_NE);
subAvg.FigE7.highF_highNE_Ca = NaN(12, 12, M_NE);
subAvg.FigE7.lowF_lowNE_HbT = NaN(12, 12, M_NE);
subAvg.FigE7.lowF_highNE_HbT = NaN(12, 12, M_NE);
subAvg.FigE7.medF_lowNE_HbT = NaN(12, 12, M_NE);
subAvg.FigE7.medF_highNE_HbT = NaN(12, 12, M_NE);

for i = 1 : M_NE
    subAvg.FigE7.lowF_lowNE_Ca(:, :, i) = mean(cat(3, ...
        FC_fr.lowF_lowNE_Ca{NE_order(i).Runs}), 3);
    subAvg.FigE7.lowF_highNE_Ca(:, :, i) = mean(cat(3, ...
        FC_fr.lowF_highNE_Ca{NE_order(i).Runs}), 3);
    subAvg.FigE7.medF_lowNE_Ca(:, :, i) = mean(cat(3, ...
        FC_fr.medF_lowNE_Ca{NE_order(i).Runs}), 3);
    subAvg.FigE7.medF_highNE_Ca(:, :, i) = mean(cat(3, ...
        FC_fr.medF_highNE_Ca{NE_order(i).Runs}), 3);
    subAvg.FigE7.highF_lowNE_Ca(:, :, i) = mean(cat(3, ...
        FC_fr.highF_lowNE_Ca{NE_order(i).Runs}), 3);
    subAvg.FigE7.highF_highNE_Ca(:, :, i) = mean(cat(3, ...
        FC_fr.highF_highNE_Ca{NE_order(i).Runs}), 3);
    subAvg.FigE7.lowF_lowNE_HbT(:, :, i) = mean(cat(3, ...
        FC_fr.lowF_lowNE_HbT{NE_order(i).Runs}), 3);
    subAvg.FigE7.lowF_highNE_HbT(:, :, i) = mean(cat(3, ...
        FC_fr.lowF_highNE_HbT{NE_order(i).Runs}), 3);
    subAvg.FigE7.medF_lowNE_HbT(:, :, i) = mean(cat(3, ...
        FC_fr.medF_lowNE_HbT{NE_order(i).Runs}), 3);
    subAvg.FigE7.medF_highNE_HbT(:, :, i) = mean(cat(3, ...
        FC_fr.medF_highNE_HbT{NE_order(i).Runs}), 3);
end

fig_savePath = fullfile(savePath, 'ExtDataFig7');
[~, ~, ~] = mkdir(fig_savePath);

%% Extended Data Fig 7A

f = figure;
f_plotFC(mean(subAvg.FigE7.lowF_lowNE_Ca, 3), 1, ...
    cmp = cmpvir, ...
    clim = [0, 1]);
colorbar off;

exportgraphics(f, fullfile(fig_savePath, 'ExtDataFig7_A1.jpg'), ...
    Resolution = 300, ...
    BackgroundColor = [1, 1, 1]);
writetable(table(mean(subAvg.FigE7.lowF_lowNE_Ca, 3)), ...
    fullfile(fig_savePath, 'ExtDataFig7_A1.csv'));

f = figure;
f_plotFC(mean(subAvg.FigE7.lowF_highNE_Ca, 3), 1, ...
    cmp = cmpvir, ...
    clim = [0, 1]);
colorbar off;

exportgraphics(f, fullfile(fig_savePath, 'ExtDataFig7_A2.jpg'), ...
    Resolution = 300, ...
    BackgroundColor = [1, 1, 1]);
writetable(table(mean(subAvg.FigE7.lowF_highNE_Ca, 3)), ...
    fullfile(fig_savePath, 'ExtDataFig7_A2.csv'));

MouseID = {log(strcmp({log.GRAB}, 'GRAB_NE')).Mouse};
g1 = cat(3, FC_fr.lowF_lowNE_Ca{strcmp({log.GRAB}, 'GRAB_NE')});
g1 = reshape(g1, 144, [])';
g2 = cat(3, FC_fr.lowF_highNE_Ca{strcmp({log.GRAB}, 'GRAB_NE')});
g2 = reshape(g2, 144, [])';
[h, p] = f_lme(MouseID, g1, g2, 0.05);

idx = logical(eye(12));
h(idx(:)) = 0;

f = figure;
f_plotFC(mean(subAvg.FigE7.lowF_highNE_Ca, 3) - ...
    mean(subAvg.FigE7.lowF_lowNE_Ca, 3), 0, ...
    cmp = cmpbbr, ...
    clim = 0.3 * [-1, 1]);
colorbar off;

exportgraphics(f, fullfile(fig_savePath, 'ExtDataFig7_A3.jpg'), ...
    Resolution = 300, ...
    BackgroundColor = [1, 1, 1]);

f_overlayStats_FC(reshape(h, 12, 12));

saveas(f, fullfile(fig_savePath, 'ExtDataFig7_A3.svg'));
writetable(table(mean(subAvg.FigE7.lowF_highNE_Ca, 3) - ...
    mean(subAvg.FigE7.lowF_lowNE_Ca, 3)), ...
    fullfile(fig_savePath, 'ExtDataFig7_A3.csv'));
writetable(table(reshape(p, 12, 12)), ...
    fullfile(fig_savePath, 'ExtDataFig7_A3_P.csv'));

%% Extended Data Fig 7B

f = figure;
f_plotFC(mean(subAvg.FigE7.medF_lowNE_Ca, 3), 1, ...
    cmp = cmpvir, ...
    clim = [0, 1]);
colorbar off;

exportgraphics(f, fullfile(fig_savePath, 'ExtDataFig7_B1.jpg'), ...
    Resolution = 300, ...
    BackgroundColor = [1, 1, 1]);
writetable(table(mean(subAvg.FigE7.medF_lowNE_Ca, 3)), ...
    fullfile(fig_savePath, 'ExtDataFig7_B1.csv'));

f = figure;
f_plotFC(mean(subAvg.FigE7.medF_highNE_Ca, 3), 1, ...
    cmp = cmpvir, ...
    clim = [0, 1]);
colorbar off;

exportgraphics(f, fullfile(fig_savePath, 'ExtDataFig7_B2.jpg'), ...
    Resolution = 300, ...
    BackgroundColor = [1, 1, 1]);
writetable(table(mean(subAvg.FigE7.medF_highNE_Ca, 3)), ...
    fullfile(fig_savePath, 'ExtDataFig7_B2.csv'));

MouseID = {log(strcmp({log.GRAB}, 'GRAB_NE')).Mouse};
g1 = cat(3, FC_fr.medF_lowNE_Ca{strcmp({log.GRAB}, 'GRAB_NE')});
g1 = reshape(g1, 144, [])';
g2 = cat(3, FC_fr.medF_highNE_Ca{strcmp({log.GRAB}, 'GRAB_NE')});
g2 = reshape(g2, 144, [])';
[h, p] = f_lme(MouseID, g1, g2, 0.05);

idx = logical(eye(12));
h(idx(:)) = 0;

f = figure;
f_plotFC(mean(subAvg.FigE7.medF_highNE_Ca, 3) - ...
    mean(subAvg.FigE7.medF_lowNE_Ca, 3), 0, ...
    cmp = cmpbbr, ...
    clim = 0.2 * [-1, 1]);
colorbar off;

exportgraphics(f, fullfile(fig_savePath, 'ExtDataFig7_B3.jpg'), ...
    Resolution = 300, ...
    BackgroundColor = [1, 1, 1]);

f_overlayStats_FC(reshape(h, 12, 12));

saveas(f, fullfile(fig_savePath, 'ExtDataFig7_B3.svg'));
writetable(table(mean(subAvg.FigE7.medF_highNE_Ca, 3) - ...
    mean(subAvg.FigE7.medF_lowNE_Ca, 3)), ...
    fullfile(fig_savePath, 'ExtDataFig7_B3.csv'));
writetable(table(reshape(p, 12, 12)), ...
    fullfile(fig_savePath, 'ExtDataFig7_B3_P.csv'));

%% Extended Data Fig 7C

f = figure;
f_plotFC(mean(subAvg.FigE7.highF_lowNE_Ca, 3), 1, ...
    cmp = cmpvir, ...
    clim = [0, 1]);
colorbar off;

exportgraphics(f, fullfile(fig_savePath, 'ExtDataFig7_C1.jpg'), ...
    Resolution = 300, ...
    BackgroundColor = [1, 1, 1]);
writetable(table(mean(subAvg.FigE7.highF_lowNE_Ca, 3)), ...
    fullfile(fig_savePath, 'ExtDataFig7_C1.csv'));

f = figure;
f_plotFC(mean(subAvg.FigE7.highF_highNE_Ca, 3), 1, ...
    cmp = cmpvir, ...
    clim = [0, 1]);
colorbar off;

exportgraphics(f, fullfile(fig_savePath, 'ExtDataFig7_C2.jpg'), ...
    Resolution = 300, ...
    BackgroundColor = [1, 1, 1]);
writetable(table(mean(subAvg.FigE7.highF_highNE_Ca, 3)), ...
    fullfile(fig_savePath, 'ExtDataFig7_C2.csv'));

MouseID = {log(strcmp({log.GRAB}, 'GRAB_NE')).Mouse};
g1 = cat(3, FC_fr.highF_lowNE_Ca{strcmp({log.GRAB}, 'GRAB_NE')});
g1 = reshape(g1, 144, [])';
g2 = cat(3, FC_fr.highF_highNE_Ca{strcmp({log.GRAB}, 'GRAB_NE')});
g2 = reshape(g2, 144, [])';
[h, p] = f_lme(MouseID, g1, g2, 0.05);

idx = logical(eye(12));
h(idx(:)) = 0;

f = figure;
f_plotFC(mean(subAvg.FigE7.highF_highNE_Ca, 3) - ...
    mean(subAvg.FigE7.highF_lowNE_Ca, 3), 0, ...
    cmp = cmpbbr, ...
    clim = 0.1 * [-1, 1]);
colorbar off;

exportgraphics(f, fullfile(fig_savePath, 'ExtDataFig7_C3.jpg'), ...
    Resolution = 300, ...
    BackgroundColor = [1, 1, 1]);

f_overlayStats_FC(reshape(h, 12, 12));

saveas(f, fullfile(fig_savePath, 'ExtDataFig7_C3.svg'));
writetable(table(mean(subAvg.FigE7.highF_highNE_Ca, 3) - ...
    mean(subAvg.FigE7.highF_lowNE_Ca, 3)), ...
    fullfile(fig_savePath, 'ExtDataFig7_C3.csv'));
writetable(table(reshape(p, 12, 12)), ...
    fullfile(fig_savePath, 'ExtDataFig7_C3_P.csv'));

%% Extended Data Fig 7D

f = figure;
f_plotFC(mean(subAvg.FigE7.lowF_lowNE_HbT, 3), 1, ...
    cmp = cmpvir, ...
    clim = [0, 1]);
colorbar off;

exportgraphics(f, fullfile(fig_savePath, 'ExtDataFig7_D1.jpg'), ...
    Resolution = 300, ...
    BackgroundColor = [1, 1, 1]);
writetable(table(mean(subAvg.FigE7.lowF_lowNE_HbT, 3)), ...
    fullfile(fig_savePath, 'ExtDataFig7_D1.csv'));

f = figure;
f_plotFC(mean(subAvg.FigE7.lowF_highNE_HbT, 3), 1, ...
    cmp = cmpvir, ...
    clim = [0, 1]);
colorbar off;

exportgraphics(f, fullfile(fig_savePath, 'ExtDataFig7_D2.jpg'), ...
    Resolution = 300, ...
    BackgroundColor = [1, 1, 1]);
writetable(table(mean(subAvg.FigE7.lowF_highNE_HbT, 3)), ...
    fullfile(fig_savePath, 'ExtDataFig7_D2.csv'));

MouseID = {log(strcmp({log.GRAB}, 'GRAB_NE')).Mouse};
g1 = cat(3, FC_fr.lowF_lowNE_HbT{strcmp({log.GRAB}, 'GRAB_NE')});
g1 = reshape(g1, 144, [])';
g2 = cat(3, FC_fr.lowF_highNE_HbT{strcmp({log.GRAB}, 'GRAB_NE')});
g2 = reshape(g2, 144, [])';
[h, p] = f_lme(MouseID, g1, g2, 0.05);

idx = logical(eye(12));
h(idx(:)) = 0;

f = figure;
f_plotFC(mean(subAvg.FigE7.lowF_highNE_HbT, 3) - ...
    mean(subAvg.FigE7.lowF_lowNE_HbT, 3), 0, ...
    cmp = cmpbbr, ...
    clim = 0.15 * [-1, 1]);
colorbar off;

exportgraphics(f, fullfile(fig_savePath, 'ExtDataFig7_D3.jpg'), ...
    Resolution = 300, ...
    BackgroundColor = [1, 1, 1]);

f_overlayStats_FC(reshape(h, 12, 12));

saveas(f, fullfile(fig_savePath, 'ExtDataFig7_D3.svg'));
writetable(table(mean(subAvg.FigE7.lowF_highNE_HbT, 3) - ...
    mean(subAvg.FigE7.lowF_lowNE_HbT, 3)), ...
    fullfile(fig_savePath, 'ExtDataFig7_D3.csv'));
writetable(table(reshape(p, 12, 12)), ...
    fullfile(fig_savePath, 'ExtDataFig7_D3_P.csv'));

%% Extended Data Fig 7E

f = figure;
f_plotFC(mean(subAvg.FigE7.medF_lowNE_HbT, 3), 1, ...
    cmp = cmpvir, ...
    clim = [0, 1]);
colorbar off;

exportgraphics(f, fullfile(fig_savePath, 'ExtDataFig7_E1.jpg'), ...
    Resolution = 300, ...
    BackgroundColor = [1, 1, 1]);
writetable(table(mean(subAvg.FigE7.medF_lowNE_HbT, 3)), ...
    fullfile(fig_savePath, 'ExtDataFig7_E1.csv'));

f = figure;
f_plotFC(mean(subAvg.FigE7.medF_highNE_HbT, 3), 1, ...
    cmp = cmpvir, ...
    clim = [0, 1]);
colorbar off;

exportgraphics(f, fullfile(fig_savePath, 'ExtDataFig7_E2.jpg'), ...
    Resolution = 300, ...
    BackgroundColor = [1, 1, 1]);
writetable(table(mean(subAvg.FigE7.medF_highNE_HbT, 3)), ...
    fullfile(fig_savePath, 'ExtDataFig7_E2.csv'));

MouseID = {log(strcmp({log.GRAB}, 'GRAB_NE')).Mouse};
g1 = cat(3, FC_fr.medF_lowNE_HbT{strcmp({log.GRAB}, 'GRAB_NE')});
g1 = reshape(g1, 144, [])';
g2 = cat(3, FC_fr.medF_highNE_HbT{strcmp({log.GRAB}, 'GRAB_NE')});
g2 = reshape(g2, 144, [])';
[h, p] = f_lme(MouseID, g1, g2, 0.05);

idx = logical(eye(12));
h(idx(:)) = 0;

f = figure;
f_plotFC(mean(subAvg.FigE7.medF_highNE_HbT, 3) - ...
    mean(subAvg.FigE7.medF_lowNE_HbT, 3), 0, ...
    cmp = cmpbbr, ...
    clim = 0.1 * [-1, 1]);
colorbar off;

exportgraphics(f, fullfile(fig_savePath, 'ExtDataFig7_E3.jpg'), ...
    Resolution = 300, ...
    BackgroundColor = [1, 1, 1]);

f_overlayStats_FC(reshape(h, 12, 12));

saveas(f, fullfile(fig_savePath, 'ExtDataFig7_E3.svg'));
writetable(table(mean(subAvg.FigE7.medF_highNE_HbT, 3) - ...
    mean(subAvg.FigE7.medF_lowNE_HbT, 3)), ...
    fullfile(fig_savePath, 'ExtDataFig7_E3.csv'));
writetable(table(reshape(p, 12, 12)), ...
    fullfile(fig_savePath, 'ExtDataFig7_E3_P.csv'));

%% Extended Data Fig 7F

regions = [2, 5, 12];

allenCaLow = mean(subAvg.FigE7.lowF_lowNE_Ca,3);
allenCaLow = allenCaLow(regions, :);
allenCaHigh = mean(subAvg.FigE7.lowF_highNE_Ca,3);
allenCaHigh = allenCaHigh(regions, :);

for i = 1 : 3
    f = figure;
    f_plotAllenMap(allenCaLow(i, :), ...
        cmp = cmpvir, ...
        mask = plotBM, ...
        clim = [0, 1]);
    f_plotAllenRegion(regions(i), 2, ...
        lineWidth = 3, ...
        color = [0, 0, 0]);
    colorbar off;

    exportgraphics(f, fullfile(fig_savePath, ...
        sprintf('ExtDataFig7_F%01i_low.jpg', i)), ...
        Resolution = 300, ...
        BackgroundColor = [1, 1, 1]);

    f = figure;
    f_plotAllenMap(allenCaHigh(i, :), ...
        cmp = cmpvir, ...
        mask = plotBM, ...
        clim = [0, 1]);
    f_plotAllenRegion(regions(i), 2, ...
        lineWidth = 3, ...
        color = [0, 0, 0]);
    colorbar off;

    exportgraphics(f, fullfile(fig_savePath, ...
        sprintf('ExtDataFig7_F%01i_high.jpg', i)), ...
        Resolution = 300, ...
        BackgroundColor = [1, 1, 1]);

    f = figure;
    f_plotAllenMap(allenCaHigh(i, :) - allenCaLow(i, :), ...
        cmp = cmpbbr, ...
        mask = plotBM, ...
        clim = 0.3 * [-1, 1]);
    f_plotAllenRegion(regions(i), 2, ...
        lineWidth = 3, ...
        color = 0.7 * [1, 1, 1]);
    colorbar off;

    exportgraphics(f, fullfile(fig_savePath, ...
        sprintf('ExtDataFig7_F%01i_diff.jpg', i)), ...
        Resolution = 300, ...
        BackgroundColor = [1, 1, 1]);
end

%% Extended Data Fig 7G

regions = [2, 5, 12];

allenCaLow = mean(subAvg.FigE7.medF_lowNE_Ca,3);
allenCaLow = allenCaLow(regions, :);
allenCaHigh = mean(subAvg.FigE7.medF_highNE_Ca,3);
allenCaHigh = allenCaHigh(regions, :);

for i = 1 : 3
    f = figure;
    f_plotAllenMap(allenCaLow(i, :), ...
        cmp = cmpvir, ...
        mask = plotBM, ...
        clim = [0, 1]);
    f_plotAllenRegion(regions(i), 2, ...
        lineWidth = 3, ...
        color = [0, 0, 0]);
    colorbar off;

    exportgraphics(f, fullfile(fig_savePath, ...
        sprintf('ExtDataFig7_G%01i_low.jpg', i)), ...
        Resolution = 300, ...
        BackgroundColor = [1, 1, 1]);

    f = figure;
    f_plotAllenMap(allenCaHigh(i, :), ...
        cmp = cmpvir, ...
        mask = plotBM, ...
        clim = [0, 1]);
    f_plotAllenRegion(regions(i), 2, ...
        lineWidth = 3, ...
        color = [0, 0, 0]);
    colorbar off;

    exportgraphics(f, fullfile(fig_savePath, ...
        sprintf('ExtDataFig7_G%01i_high.jpg', i)), ...
        Resolution = 300, ...
        BackgroundColor = [1, 1, 1]);

    f = figure;
    f_plotAllenMap(allenCaHigh(i, :) - allenCaLow(i, :), ...
        cmp = cmpbbr, ...
        mask = plotBM, ...
        clim = 0.2 * [-1, 1]);
    f_plotAllenRegion(regions(i), 2, ...
        lineWidth = 3, ...
        color = 0.7 * [1, 1, 1]);
    colorbar off;

    exportgraphics(f, fullfile(fig_savePath, ...
        sprintf('ExtDataFig7_G%01i_diff.jpg', i)), ...
        Resolution = 300, ...
        BackgroundColor = [1, 1, 1]);
end

%% Extended Data Fig 7H

regions = [2, 5, 12];

allenCaLow = mean(subAvg.FigE7.highF_lowNE_Ca,3);
allenCaLow = allenCaLow(regions, :);
allenCaHigh = mean(subAvg.FigE7.highF_highNE_Ca,3);
allenCaHigh = allenCaHigh(regions, :);

for i = 1 : 3
    f = figure;
    f_plotAllenMap(allenCaLow(i, :), ...
        cmp = cmpvir, ...
        mask = plotBM, ...
        clim = [0, 1]);
    f_plotAllenRegion(regions(i), 2, ...
        lineWidth = 3, ...
        color = [0, 0, 0]);
    colorbar off;

    exportgraphics(f, fullfile(fig_savePath, ...
        sprintf('ExtDataFig7_H%01i_low.jpg', i)), ...
        Resolution = 300, ...
        BackgroundColor = [1, 1, 1]);

    f = figure;
    f_plotAllenMap(allenCaHigh(i, :), ...
        cmp = cmpvir, ...
        mask = plotBM, ...
        clim = [0, 1]);
    f_plotAllenRegion(regions(i), 2, ...
        lineWidth = 3, ...
        color = [0, 0, 0]);
    colorbar off;

    exportgraphics(f, fullfile(fig_savePath, ...
        sprintf('ExtDataFig7_H%01i_high.jpg', i)), ...
        Resolution = 300, ...
        BackgroundColor = [1, 1, 1]);

    f = figure;
    f_plotAllenMap(allenCaHigh(i, :) - allenCaLow(i, :), ...
        cmp = cmpbbr, ...
        mask = plotBM, ...
        clim = 0.1 * [-1, 1]);
    f_plotAllenRegion(regions(i), 2, ...
        lineWidth = 3, ...
        color = 0.7 * [1, 1, 1]);
    colorbar off;

    exportgraphics(f, fullfile(fig_savePath, ...
        sprintf('ExtDataFig7_H%01i_diff.jpg', i)), ...
        Resolution = 300, ...
        BackgroundColor = [1, 1, 1]);
end

%% Extended Data Fig 7I

regions = [2, 5, 12];

allenCaLow = mean(subAvg.FigE7.lowF_lowNE_HbT,3);
allenCaLow = allenCaLow(regions, :);
allenCaHigh = mean(subAvg.FigE7.lowF_highNE_HbT,3);
allenCaHigh = allenCaHigh(regions, :);

for i = 1 : 3
    f = figure;
    f_plotAllenMap(allenCaLow(i, :), ...
        cmp = cmpvir, ...
        mask = plotBM, ...
        clim = [0, 1]);
    f_plotAllenRegion(regions(i), 2, ...
        lineWidth = 3, ...
        color = [0, 0, 0]);
    colorbar off;

    exportgraphics(f, fullfile(fig_savePath, ...
        sprintf('ExtDataFig7_I%01i_low.jpg', i)), ...
        Resolution = 300, ...
        BackgroundColor = [1, 1, 1]);

    f = figure;
    f_plotAllenMap(allenCaHigh(i, :), ...
        cmp = cmpvir, ...
        mask = plotBM, ...
        clim = [0, 1]);
    f_plotAllenRegion(regions(i), 2, ...
        lineWidth = 3, ...
        color = [0, 0, 0]);
    colorbar off;

    exportgraphics(f, fullfile(fig_savePath, ...
        sprintf('ExtDataFig7_I%01i_high.jpg', i)), ...
        Resolution = 300, ...
        BackgroundColor = [1, 1, 1]);

    f = figure;
    f_plotAllenMap(allenCaHigh(i, :) - allenCaLow(i, :), ...
        cmp = cmpbbr, ...
        mask = plotBM, ...
        clim = 0.15 * [-1, 1]);
    f_plotAllenRegion(regions(i), 2, ...
        lineWidth = 3, ...
        color = 0.7 * [1, 1, 1]);
    colorbar off;

    exportgraphics(f, fullfile(fig_savePath, ...
        sprintf('ExtDataFig7_I%01i_diff.jpg', i)), ...
        Resolution = 300, ...
        BackgroundColor = [1, 1, 1]);
end

%% Extended Data Fig 7J

regions = [2, 5, 12];

allenCaLow = mean(subAvg.FigE7.medF_lowNE_HbT,3);
allenCaLow = allenCaLow(regions, :);
allenCaHigh = mean(subAvg.FigE7.medF_highNE_HbT,3);
allenCaHigh = allenCaHigh(regions, :);

for i = 1 : 3
    f = figure;
    f_plotAllenMap(allenCaLow(i, :), ...
        cmp = cmpvir, ...
        mask = plotBM, ...
        clim = [0, 1]);
    f_plotAllenRegion(regions(i), 2, ...
        lineWidth = 3, ...
        color = [0, 0, 0]);
    colorbar off;

    exportgraphics(f, fullfile(fig_savePath, ...
        sprintf('ExtDataFig7_J%01i_low.jpg', i)), ...
        Resolution = 300, ...
        BackgroundColor = [1, 1, 1]);

    f = figure;
    f_plotAllenMap(allenCaHigh(i, :), ...
        cmp = cmpvir, ...
        mask = plotBM, ...
        clim = [0, 1]);
    f_plotAllenRegion(regions(i), 2, ...
        lineWidth = 3, ...
        color = [0, 0, 0]);
    colorbar off;

    exportgraphics(f, fullfile(fig_savePath, ...
        sprintf('ExtDataFig7_J%01i_high.jpg', i)), ...
        Resolution = 300, ...
        BackgroundColor = [1, 1, 1]);

    f = figure;
    f_plotAllenMap(allenCaHigh(i, :) - allenCaLow(i, :), ...
        cmp = cmpbbr, ...
        mask = plotBM, ...
        clim = 0.1 * [-1, 1]);
    f_plotAllenRegion(regions(i), 2, ...
        lineWidth = 3, ...
        color = 0.7 * [1, 1, 1]);
    colorbar off;

    exportgraphics(f, fullfile(fig_savePath, ...
        sprintf('ExtDataFig7_J%01i_diff.jpg', i)), ...
        Resolution = 300, ...
        BackgroundColor = [1, 1, 1]);
end